
#os: Visual Studio 2014 CTP4

platform:
  - x64
  - x86

install:
  - IF %PLATFORM% EQU x86 (SET PNAME=win-python-2.7.8-32.7z) ELSE (SET PNAME=win-python-2.7.8-64.7z)
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:platform.exe" -FileName vcredist.exe
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-$env:platform-v3.0.0-rc1-246-g5361d21.7z" -FileName mapnik-sdk.7z
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/deps/$env:PNAME" -FileName python.7z
  - vcredist /quiet
  - 7z x mapnik-sdk.7z > nul
  - 7z x python.7z > nul
  # appending to PATH within parantheses doesn't work, workarround with %~PATH% doesn't either
  - IF %PLATFORM% EQU x86 SET PATH=%CD%\python2-x86-32;%PATH%
  - IF %PLATFORM% EQU x64 SET PATH=%CD%\python2;%PATH%
  # we have to CD into the directories to call the batch files
  # otherwise env vars have wrong paths
  # this happens only on AppVeyor - NOT necessary locally
  - cd mapnik-sdk
  - set-env-vars.bat
  - ECHO %PYTHONPATH%
  - ECHO %ICU_DATA%
  - cd bin
  - mapnik-config --fonts
  - cd C:\projects\mapnik-gyp\mapnik-sdk\python\2.7\site-packages
  - ECHO %CD%
  - SET
  - where python
  - python -V
  - python -c "import sys; print('python 64bit' if sys.maxsize > 2**32 else 'python 32bit');"
  - python -c "import mapnik"
  - python C:\projects\mapnik-gyp\mapnik-sdk\demo\python\rundemo.py

build: OFF
test: OFF
deploy: OFF
